### ISSUE TITLE
Array Algebra

### ISSUE THREAD

**Issue by ericdill** [Nikea/scikit-xray#10]
Description
----
Array algebra is mathematical operations on arrays that can be exclusively handled by numpy whenever a user is directly writing python and thus should not be included in the NSLS2 library.  For doing array algebra in a GUI, we will need to wrap these numpy operations and so these wrappers belong in VisTrails layer.  Thus, see NSLS-II/userpackages Issue 2 https://github.com/NSLS-II/userpackages/issues/2

**Comment by danielballan** [comment]
Solved by @giltis and docs.
