### ISSUE TITLE
Image Construction

### ISSUE THREAD

**Issue by ericdill** [Nikea/scikit-xray#20]
Description
====
This use case is primarily related to SRX.  IIRC, one of the data collection modes on SRX is to raster the sample through the beam, collecting an MCA spectrum for each sample position.  This MCA spectrum at each position is then used to reconstruct a 2-D image of the sample.  @tacaswell can probably make this description significantly more verbose

Problems that need to be solved for this Issue
====
- [ ] SRX Approval

**Comment by danielballan** [comment]
Waiting on a PR from @licode, same as #253
