### ISSUE TITLE
Set up air speed velocity (asv)

### ISSUE THREAD

**Issue by ericdill** [Nikea/scikit-xray#207]
Airspeed velocity (asv) is a library that allows you to track the historical performance of various benchmarks on a library.  Before asv can be stood up, a few other infrastructurey things need to fall into place.

**Comment by danielballan** [comment]
I am willing to be assigned this if @tacaswell wants to hand it off.

**Comment by danielballan** [comment]
We will use asv to run tests on real data, where it is hard to define an exact correct value or a good tolerance. Instead of pass/fail, we will keep an eye on these results manually, using asv to track the outputs.

**Comment by danielballan** [comment]
See https://github.com/Nikea/scikit-xray-bench
