### ISSUE TITLE
detector2D_to_1D is missing from skxray.core

### ISSUE THREAD

**Issue by decarlof** [Nikea/scikit-xray#215]
=>

python examples/2d_radial_integration.py
Traceback (most recent call last):
  File "examples/2d_radial_integration.py", line 42, in <module>
    from skxray.core import detector2D_to_1D
ImportError: cannot import name detector2D_to_1D

**Comment by tacaswell** [comment]
Looking at this example at has a good many _other_ issues un-related to the import failure.  This probably should be moved the examles repo as well.

**Comment by danielballan** [comment]
In the doc overhaul, I removed the entire examples/ directory. This and the other example (which also has serious problems) will be reinstated in notebook form in the demo repo.

**Comment by tacaswell** [comment]
ahh, so that is where it went.

Closing this as it should be moved to the other repo. Leaving https://github.com/tacaswell/scikit-xray/tree/example_fix and 74f3158f3d49783fc9db5bfa43887764877afca3 as references on how to start to rework the exmple.
