### ISSUE TITLE
Image Corrections: Dark Current Subtraction

### ISSUE THREAD

**Issue by ericdill** [Nikea/scikit-xray#24]
Description
====
The dark current subtraction at the lowest level is actually very simple, as it is merely the measured detector image with the shutter open minus some reference detector image with the shutter closed.  The trouble with this requirement is that there is no pre-determined method by which dark current images are collected during the experiment.  In the worst case, the dark current images (shutter closed) will be randomly interspersed with the shutter open images.  

Someone, somewhere is going to have to correlate the shutter_open images with the shutter_closed images so that they can be subtracted from each other.  We can probably make a function that works by taking in a run_header nested dictionary from the data broker and spits out a series of dark current subtracted images.  In fact, that might be the best approach, for now.

**Comment by danielballan** [comment]
This is handled by the muxer, and will be handled also by a pims class. Either one works.
