### ISSUE TITLE
Convolution function

### ISSUE THREAD

**Issue by licode** [Nikea/scikit-xray#258]
Compare convolution function from CDI PR and scipy convolution functions. Check boundary conditions or any interpolation effects from scipy convolution.

**Comment by licode** [comment]
![figure_1](https://cloud.githubusercontent.com/assets/4765544/7091563/958e8d74-df78-11e4-94e4-1e771d1c0a22.png)

**Comment by licode** [comment]
This is the result of convolution between two gaussian using two different calls. Difference is shown only on boundary part. This is fine for CDI calculation as we only choose the center part of convolution. The number of data array is odd.

When number of data array is even, we can see one pixel shift.

**Comment by danielballan** [comment]
The scipy result looks more correct to me. The convolution of two Gaussians is a Gaussian, and the blue curve looks more Gaussian. Can you share the code you used to create this plot?

**Comment by ericdill** [comment]
Turns out that the implementation in #257 is faster than `scipy.signal.fftconvolve`. See this notebook: http://nbviewer.ipython.org/gist/anonymous/7ce4df28c34fdcb96729

**Comment by ericdill** [comment]
Also, @licode has just informed me that the central portion of the gaussian curve is the only bit that gets used, where the central portion is roughly defined by where the maximum of the peak drops below 20% of the peak height.

**Comment by danielballan** [comment]
Would you also try `np.convole` and `scipy.signal.convolve` in that benchmarking notebook?

**Comment by ericdill** [comment]
@danielballan here ya go. Also plotted the output 

http://nbviewer.ipython.org/gist/anonymous/4e670bd7a03b456b34fe

**Comment by tacaswell** [comment]
There is a factor of 100 scaling difference...

**Comment by ericdill** [comment]
@licode any idea why your convolution function is 2 orders of magnitude
different?

**Comment by danielballan** [comment]
Taking a step back, what is the goal of this function? It looks like it
does blurring in N dimensions, but your plot suggests that this is one
dimensional, performed in parallel over many 1D arrays. Maybe you can
explain in person.

**Comment by licode** [comment]
I probably didn't explain the plot clearly. I did convolution between two 2D gaussians, say final results have size [100,100]. But I only plot the central line[50,:] of each 2D image to show the difference.

**Comment by danielballan** [comment]
I see. It's unusual to convolve two things of the same size because of edge
effects. In the case of Gaussians (or any peak-like function) we can safely
assert that any pixels outside the domain of the image are zero. I guess
that's why convolving two equal-sized images works in this case.

I'd like to follow up a little more to satisfy my own curiosity about the
various convolution functions, their differences, and their performance.

**Comment by licode** [comment]
Guys, I am so boring so I run the test again. It found that we can twist argument 'boundary' in convolve2d to make the result either the same as output from cdi.convolution or fftconvolve.
http://nbviewer.ipython.org/gist/licode/b1149e4d4c283364b357

When we set boundary = wrap, the aliasing effect is quite strong. So the value on the boundary is higher, because of periodic property of FFT.

**Comment by licode** [comment]
So all the methods are correct depending how you choose the boundary condition. The 100 scaling effect is because of normal factor 1/N in cdi.convolution. I need to double check this.

Based on my understand, the absolute value is not important. The use case is to convolve one 2D function with a gaussian, and return the index of the convoluted 2d array where the value is above, say 30% of maximum value. Basically we want a smooth effect with a threshold cut. Same for 3D case.
