### ISSUE TITLE
Determine detector tilt angles

### ISSUE THREAD

**Issue by ericdill** [Nikea/scikit-xray#37]
Description
====
2-D detectors are never *perfectly* perpendicular to the incident beam (call it z).  In order to compute pixel positions, the detector rotation about the x- and y- directions need to be taken into account.

Problems to be solved
====
 - [ ] Determine if code exists to compute detector tilt angles from a calibration standard
 - [ ] Wrap that code if possible

Otherwise:
 - [ ] Figure out what calibration standards are required
 - [ ] Write code to compute detector tilt angles from the required calibration standards

See Also
====
#41

**Comment by danielballan** [comment]
A more thorough description of this issue is in #119. Head over there to follow progress.
